In [14]:
import numpy as np
z=np.zeros(6)
print(z) #零
print(np.empty((2,3,4))) #幾維陳列,幾筆資料,每筆資料有多少
print(np.arange(2,10,2)) #序列

[0. 0. 0. 0. 0. 0.]
[[[6.23042070e-307 1.86918699e-306 1.69121096e-306 1.29061074e-306]
  [1.69119873e-306 1.78019082e-306 7.56587585e-307 1.37961302e-306]
  [1.05699242e-307 8.01097889e-307 1.78020169e-306 7.56601165e-307]]

 [[1.02359984e-306 1.33510679e-306 2.22522597e-306 1.33511018e-306]
  [6.23057689e-307 9.45754852e-308 1.27946076e-307 1.05700515e-307]
  [1.11261774e-306 1.29060871e-306 8.34424766e-308 2.12203497e-312]]]
[2 4 6 8]


# ndarray的進階操作

In [16]:
my_array=np.arange(10)
print(my_array)
print(my_array[0])
print(my_array[0:5])

[0 1 2 3 4 5 6 7 8 9]
0
[0 1 2 3 4]


In [20]:
my_2d_array= np.array([np.arange(0,5), np.arange(5,10)])
print(my_2d_array)
print(my_2d_array[1,:])
print(my_2d_array[:,1])
print(my_2d_array[1,1])

[[0 1 2 3 4]
 [5 6 7 8 9]]
[5 6 7 8 9]
[1 6]
6


In [25]:
my_array=np.arange(0,10)
print(my_array)
print(" ")
print(my_array.shape)
print(" ")
my_2d_array= my_array.reshape(2,5)
print(my_2d_array)
print(" ")
print((np.arange(0,100).reshape(10,10)))

[0 1 2 3 4 5 6 7 8 9]
 
(10,)
 
[[0 1 2 3 4]
 [5 6 7 8 9]]
 
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


# numpy 的空值nan


In [28]:
b = np.array([56,8,19,14,np.nan])
print(b)

[56.  8. 19. 14. nan]
